#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  python3 "$SCRIPT_DIR/generate_security_env.py" --output "$ENV_FILE"
fi

set -a
# Values generated by generate_security_env.py contain no shell metacharacters.
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [[ ${#MEETILY_BACKEND_TOKEN} -lt 32 || ${#MEETILY_WHISPER_TOKEN} -lt 32 ]]; then
  echo "Security tokens are missing or too short. Regenerate backend/.env." >&2
  exit 1
fi

PACKAGE_DIR="$SCRIPT_DIR/whisper-server-package"
MODEL_PATH="${WHISPER_MODEL:-models/ggml-large-v3-turbo-q5_0.bin}"
WHISPER_PORT="${WHISPER_PORT:-8178}"
WHISPER_LANGUAGE="${WHISPER_LANGUAGE:-th}"

[[ -x "$PACKAGE_DIR/run-server.sh" ]] || { echo "Missing $PACKAGE_DIR/run-server.sh; run build_whisper.sh first." >&2; exit 1; }
[[ -f "$PACKAGE_DIR/$MODEL_PATH" ]] || { echo "Missing Whisper model: $PACKAGE_DIR/$MODEL_PATH" >&2; exit 1; }
[[ -f "$SCRIPT_DIR/app/main.py" ]] || { echo "Missing Python backend app/main.py" >&2; exit 1; }
[[ -f "$SCRIPT_DIR/venv/bin/activate" ]] || { echo "Missing Python virtual environment; run the build script first." >&2; exit 1; }

WHISPER_PID=""
BACKEND_PID=""
cleanup() {
  [[ -n "$BACKEND_PID" ]] && kill "$BACKEND_PID" 2>/dev/null || true
  [[ -n "$WHISPER_PID" ]] && kill "$WHISPER_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

(
  cd "$PACKAGE_DIR"
  exec ./run-server.sh \
    --model "$MODEL_PATH" \
    --host 127.0.0.1 \
    --port "$WHISPER_PORT" \
    --language "$WHISPER_LANGUAGE" \
    --diarize \
    --print-progress
) &
WHISPER_PID=$!

# Start the authenticated legacy API on loopback. It reads the same .env file.
# shellcheck disable=SC1091
source "$SCRIPT_DIR/venv/bin/activate"
python "$SCRIPT_DIR/app/main.py" &
BACKEND_PID=$!

sleep 2
kill -0 "$WHISPER_PID" 2>/dev/null || { echo "Whisper server failed to start." >&2; exit 1; }
kill -0 "$BACKEND_PID" 2>/dev/null || { echo "Python backend failed to start." >&2; exit 1; }

echo "Meetily local services started securely on 127.0.0.1. Tokens were not printed."
wait "$BACKEND_PID" "$WHISPER_PID"
